# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prettier

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development ]

jobs:
  format:
    runs-on: windows-latest
    name: "Check formatting"
    working-directory: ./gouden-draak

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        working-directory: ./gouden-draak
        uses: actions/checkout@v2
      - name: Set up Node
        working-directory: ./gouden-draak
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Prettier
        working-directory: ./gouden-draak
        run: npm install

      - name: Check formatting
        working-directory: ./gouden-draak
        run: npm run format:check
